<script setup>
import { computed, onMounted, ref } from 'vue'
import { Clock3, PackageCheck, RefreshCw, Truck, CheckCircle2 } from 'lucide-vue-next'
import PageHeader from '@/components/common/PageHeader.vue'
import DashboardKpiCard from '@/components/dashboard/DashboardKpiCard.vue'
import BaseCard from '@/components/common/BaseCard.vue'
import { envioService } from '@/services/envioService'
import { catalogoService } from '@/services/catalogoService'
import { useUiStore } from '@/stores/uiStore'
const ui=useUiStore(),loading=ref(true),shipments=ref([]),states=ref([]);const counts=computed(()=>{const codes=shipments.value.map(x=>states.value.find(s=>s.estadoEnvioId===x.estadoEnvioId)?.codigo);return[{title:'Pendientes de confirmación',value:codes.filter(x=>x==='PENDIENTE_CONFIRMACION_TRANSPORTE').length,icon:Clock3,tone:'amber'},{title:'Confirmados',value:codes.filter(x=>x==='CONFIRMADO_TRANSPORTACION').length,icon:PackageCheck,tone:'blue'},{title:'En tránsito',value:codes.filter(x=>x==='EN_TRANSITO').length,icon:Truck,tone:'indigo'},{title:'Recibidos',value:codes.filter(x=>['RECIBIDO_TRANSPORTACION','RECIBIDO_FILIAL'].includes(x)).length,icon:CheckCircle2,tone:'green'}]});async function load(){loading.value=true;try{const [e,s]=await Promise.all([envioService.list(),catalogoService.states()]);shipments.value=e.data||[];states.value=s.data||[]}catch(e){ui.notify(e.userMessage||'No fue posible cargar el dashboard de transportación.','error')}finally{loading.value=false}}onMounted(load)
</script>
<template><div class="dashboard-page transport-dashboard"><PageHeader title="Dashboard de transportación" subtitle="Resumen operativo del traslado de envíos"><button class="btn btn-ghost" :disabled="loading" @click="load"><RefreshCw :size="15"/> Actualizar</button><RouterLink class="btn btn-secondary" to="/transportacion/operaciones">Ver operaciones</RouterLink><RouterLink class="btn btn-primary" to="/transportacion/nuevo">Registrar vehículo y chofer</RouterLink></PageHeader><div class="dashboard-tabs"><RouterLink class="active" to="/transportacion">Dashboard</RouterLink><RouterLink to="/transportacion/operaciones">Operaciones</RouterLink></div><div class="dashboard-secondary-grid transport-kpis"><DashboardKpiCard v-for="stat in counts" :key="stat.title" v-bind="stat"/></div><BaseCard title="Operación de transportación"><div v-if="loading" class="loading-state">Cargando métricas…</div><div v-else class="transport-dashboard-note"><Truck :size="32"/><span>Las métricas se calculan con los estados reales de los envíos. Utiliza Operaciones para filtrar, consultar y abrir el detalle de cada envío.</span></div></BaseCard></div></template>
