USE SistemaEnviosDB;
GO
IF NOT EXISTS (SELECT 1 FROM dbo.EstadosEnvio WHERE Codigo=N'TRANSPORTE_ASIGNADO') INSERT dbo.EstadosEnvio(Codigo,Nombre,Descripcion,EsFinal,Activo) VALUES(N'TRANSPORTE_ASIGNADO',N'Chofer asignado',N'Transportación asignó el chofer al envío.',0,1);
IF NOT EXISTS (SELECT 1 FROM dbo.EstadosEnvio WHERE Codigo=N'DESPACHADO_TRANSPORTACION') INSERT dbo.EstadosEnvio(Codigo,Nombre,Descripcion,EsFinal,Activo) VALUES(N'DESPACHADO_TRANSPORTACION',N'Despachado por Transportación',N'Transportación despachó el envío hacia la filial.',0,1);
IF NOT EXISTS (SELECT 1 FROM dbo.EstadosEnvio WHERE Codigo=N'EN_TRANSPORTACION') INSERT dbo.EstadosEnvio(Codigo,Nombre,Descripcion,EsFinal,Activo) VALUES(N'EN_TRANSPORTACION',N'En Transportación',N'El envío fue recibido por el área de Transportación.',0,1);
IF NOT EXISTS (SELECT 1 FROM dbo.TransicionesEstadoEnvio t JOIN dbo.EstadosEnvio a ON a.EstadoEnvioId=t.EstadoOrigenId JOIN dbo.EstadosEnvio b ON b.EstadoEnvioId=t.EstadoDestinoId WHERE a.Codigo=N'DESPACHADO_TECNOLOGIA' AND b.Codigo=N'EN_TRANSPORTACION') INSERT dbo.TransicionesEstadoEnvio(EstadoOrigenId,EstadoDestinoId,Activo) SELECT a.EstadoEnvioId,b.EstadoEnvioId,1 FROM dbo.EstadosEnvio a CROSS JOIN dbo.EstadosEnvio b WHERE a.Codigo=N'DESPACHADO_TECNOLOGIA' AND b.Codigo=N'EN_TRANSPORTACION';
IF NOT EXISTS (SELECT 1 FROM dbo.TransicionesEstadoEnvio t JOIN dbo.EstadosEnvio a ON a.EstadoEnvioId=t.EstadoOrigenId JOIN dbo.EstadosEnvio b ON b.EstadoEnvioId=t.EstadoDestinoId WHERE a.Codigo=N'EN_TRANSPORTACION' AND b.Codigo=N'TRANSPORTE_ASIGNADO') INSERT dbo.TransicionesEstadoEnvio(EstadoOrigenId,EstadoDestinoId,Activo) SELECT a.EstadoEnvioId,b.EstadoEnvioId,1 FROM dbo.EstadosEnvio a CROSS JOIN dbo.EstadosEnvio b WHERE a.Codigo=N'EN_TRANSPORTACION' AND b.Codigo=N'TRANSPORTE_ASIGNADO';
IF NOT EXISTS (SELECT 1 FROM dbo.TransicionesEstadoEnvio t JOIN dbo.EstadosEnvio a ON a.EstadoEnvioId=t.EstadoOrigenId JOIN dbo.EstadosEnvio b ON b.EstadoEnvioId=t.EstadoDestinoId WHERE a.Codigo=N'DESPACHADO_TECNOLOGIA' AND b.Codigo=N'TRANSPORTE_ASIGNADO') INSERT dbo.TransicionesEstadoEnvio(EstadoOrigenId,EstadoDestinoId,Activo) SELECT a.EstadoEnvioId,b.EstadoEnvioId,1 FROM dbo.EstadosEnvio a CROSS JOIN dbo.EstadosEnvio b WHERE a.Codigo=N'DESPACHADO_TECNOLOGIA' AND b.Codigo=N'TRANSPORTE_ASIGNADO';
IF NOT EXISTS (SELECT 1 FROM dbo.TransicionesEstadoEnvio t JOIN dbo.EstadosEnvio a ON a.EstadoEnvioId=t.EstadoOrigenId JOIN dbo.EstadosEnvio b ON b.EstadoEnvioId=t.EstadoDestinoId WHERE a.Codigo=N'TRANSPORTE_ASIGNADO' AND b.Codigo=N'DESPACHADO_TRANSPORTACION') INSERT dbo.TransicionesEstadoEnvio(EstadoOrigenId,EstadoDestinoId,Activo) SELECT a.EstadoEnvioId,b.EstadoEnvioId,1 FROM dbo.EstadosEnvio a CROSS JOIN dbo.EstadosEnvio b WHERE a.Codigo=N'TRANSPORTE_ASIGNADO' AND b.Codigo=N'DESPACHADO_TRANSPORTACION';
IF NOT EXISTS (SELECT 1 FROM dbo.TransicionesEstadoEnvio t JOIN dbo.EstadosEnvio a ON a.EstadoEnvioId=t.EstadoOrigenId JOIN dbo.EstadosEnvio b ON b.EstadoEnvioId=t.EstadoDestinoId WHERE a.Codigo=N'DESPACHADO_TRANSPORTACION' AND b.Codigo=N'EN_TRANSITO') INSERT dbo.TransicionesEstadoEnvio(EstadoOrigenId,EstadoDestinoId,Activo) SELECT a.EstadoEnvioId,b.EstadoEnvioId,1 FROM dbo.EstadosEnvio a CROSS JOIN dbo.EstadosEnvio b WHERE a.Codigo=N'DESPACHADO_TRANSPORTACION' AND b.Codigo=N'EN_TRANSITO';
GO
