using Microsoft.EntityFrameworkCore;
using SistemaEnvios.Application.Common;
using SistemaEnvios.Application.DTOs.Transportes;
using SistemaEnvios.Application.Interfaces.Repositories;
using SistemaEnvios.Application.Interfaces.Security;
using SistemaEnvios.Application.Interfaces.Services;
using SistemaEnvios.Domain.Entities;
using SistemaEnvios.Domain.Enums;
using SistemaEnvios.Infrastructure.Persistence;

namespace SistemaEnvios.Infrastructure.Services.Transportes;
public sealed class CatalogoTransporteService(SistemaEnviosDbContext db, IUnitOfWork uow, IUserContext users) : ICatalogoTransporteService
{
    public async Task<Result<IReadOnlyCollection<TipoTransporteResponse>>> ListarTiposAsync(bool soloActivos=true,CancellationToken ct=default){var q=db.TiposTransporte.AsNoTracking();if(soloActivos)q=q.Where(x=>x.Activo);var r=await q.OrderBy(x=>x.Nombre).Select(x=>new TipoTransporteResponse(x.TipoTransporteId,x.Codigo,x.Nombre,x.Estrategia,x.Activo)).ToListAsync(ct);return Result<IReadOnlyCollection<TipoTransporteResponse>>.Success(r);}
    public async Task<Result<int>> CrearTipoAsync(GuardarTipoTransporteRequest r,CancellationToken ct=default){if(users.UserId is not Guid u)return Result<int>.Failure("Usuario no identificado.",ErrorType.Unauthorized);var v=ValidarTipo(r);if(v is not null)return Result<int>.Failure(v,ErrorType.Validation);var c=r.Codigo.Trim().ToUpperInvariant();if(await db.TiposTransporte.AnyAsync(x=>x.Codigo==c,ct))return Result<int>.Failure("El código ya existe.",ErrorType.Conflict);var x=new TipoTransporte{Codigo=c,Nombre=r.Nombre.Trim(),Estrategia=r.Estrategia,Activo=true,FechaCreacion=DateTime.UtcNow,UsuarioCreacionId=u};db.Add(x);await uow.SaveChangesAsync(ct);return Result<int>.Success(x.TipoTransporteId);}
    public async Task<Result> ActualizarTipoAsync(GuardarTipoTransporteRequest r,CancellationToken ct=default){if(users.UserId is not Guid u)return Result.Failure("Usuario no identificado.",ErrorType.Unauthorized);var x=await db.TiposTransporte.FindAsync([r.TipoTransporteId],ct);if(x is null)return Result.Failure("El tipo no existe.",ErrorType.NotFound);if(x.Estrategia!=r.Estrategia&&await db.Transportes.AnyAsync(t=>t.TipoTransporteId==x.TipoTransporteId,ct))return Result.Failure("No se puede cambiar la estrategia de un tipo utilizado.",ErrorType.Conflict);x.Nombre=r.Nombre.Trim();x.Estrategia=r.Estrategia;x.FechaModificacion=DateTime.UtcNow;x.UsuarioModificacionId=u;await uow.SaveChangesAsync(ct);return Result.Success();}
    public async Task<Result> CambiarTipoActivoAsync(int id,bool activo,CancellationToken ct=default)=>await CambiarActivoTipo(id,activo,ct);
    private async Task<Result> CambiarActivoTipo(int id,bool activo,CancellationToken ct){if(users.UserId is not Guid u)return Result.Failure("Usuario no identificado.",ErrorType.Unauthorized);var x=await db.TiposTransporte.FindAsync([id],ct);if(x is null)return Result.Failure("El tipo no existe.",ErrorType.NotFound);x.Activo=activo;x.FechaModificacion=DateTime.UtcNow;x.UsuarioModificacionId=u;await uow.SaveChangesAsync(ct);return Result.Success();}
    public async Task<Result<IReadOnlyCollection<ChoferInternoResponse>>> ListarChoferesAsync(bool soloActivos=true,CancellationToken ct=default){var q=db.ChoferesInternos.AsNoTracking();if(soloActivos)q=q.Where(x=>x.Activo);var r=await q.OrderBy(x=>x.NombreCompleto).Select(x=>new ChoferInternoResponse(x.ChoferInternoId,x.NombreCompleto,x.NumeroEmpleado,x.Activo)).ToListAsync(ct);return Result<IReadOnlyCollection<ChoferInternoResponse>>.Success(r);}
    public async Task<Result<int>> CrearChoferAsync(GuardarChoferInternoRequest r,CancellationToken ct=default){if(users.UserId is not Guid u)return Result<int>.Failure("Usuario no identificado.",ErrorType.Unauthorized);var v=ValidarChofer(r);if(v is not null)return Result<int>.Failure(v,ErrorType.Validation);var n=r.NumeroEmpleado.Trim().ToUpperInvariant();if(await db.ChoferesInternos.AnyAsync(x=>x.NumeroEmpleado==n,ct))return Result<int>.Failure("El número de empleado ya existe.",ErrorType.Conflict);var x=new ChoferInterno{NombreCompleto=r.NombreCompleto.Trim(),NumeroEmpleado=n,Activo=true,FechaCreacion=DateTime.UtcNow,UsuarioCreacionId=u};db.Add(x);await uow.SaveChangesAsync(ct);return Result<int>.Success(x.ChoferInternoId);}
    public async Task<Result> ActualizarChoferAsync(GuardarChoferInternoRequest r,CancellationToken ct=default){if(users.UserId is not Guid u)return Result.Failure("Usuario no identificado.",ErrorType.Unauthorized);var x=await db.ChoferesInternos.FindAsync([r.ChoferInternoId],ct);if(x is null)return Result.Failure("El chofer no existe.",ErrorType.NotFound);var n=r.NumeroEmpleado.Trim().ToUpperInvariant();if(await db.ChoferesInternos.AnyAsync(y=>y.ChoferInternoId!=x.ChoferInternoId&&y.NumeroEmpleado==n,ct))return Result.Failure("El número de empleado ya existe.",ErrorType.Conflict);x.NombreCompleto=r.NombreCompleto.Trim();x.NumeroEmpleado=n;x.FechaModificacion=DateTime.UtcNow;x.UsuarioModificacionId=u;await uow.SaveChangesAsync(ct);return Result.Success();}
    public async Task<Result> CambiarChoferActivoAsync(int id,bool activo,CancellationToken ct=default){if(users.UserId is not Guid u)return Result.Failure("Usuario no identificado.",ErrorType.Unauthorized);var x=await db.ChoferesInternos.FindAsync([id],ct);if(x is null)return Result.Failure("El chofer no existe.",ErrorType.NotFound);x.Activo=activo;x.FechaModificacion=DateTime.UtcNow;x.UsuarioModificacionId=u;await uow.SaveChangesAsync(ct);return Result.Success();}
    private static string? ValidarTipo(GuardarTipoTransporteRequest r)=>string.IsNullOrWhiteSpace(r.Codigo)||string.IsNullOrWhiteSpace(r.Nombre)||!Enum.IsDefined(r.Estrategia)?"Código, nombre y estrategia válida son requeridos.":null;
    private static string? ValidarChofer(GuardarChoferInternoRequest r)=>string.IsNullOrWhiteSpace(r.NombreCompleto)||string.IsNullOrWhiteSpace(r.NumeroEmpleado)?"Nombre y número de empleado son requeridos.":null;
}
